spring:
  datasource:
    url: jdbc:h2:mem:localdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        '[format_sql]': true
  h2:
    console:
      enabled: true
      path: /h2-console
